# Generated by Django 5.2.16 on 2026-07-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.CharField(blank=True, max_length=32)),
                ('retail_price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'retail_price'], name='fuel_fuelst_state_f71b8e_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_fuelst_latitud_e7de73_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('source', models.CharField(default='nominatim', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'city'], name='fuel_geocod_state_d9b8f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('city', 'state'), name='uniq_geocode_city_state')],
            },
        ),
    ]
